
language: ruby
rvm:
  - 2.0.0
postgres:
  adapter: postgresql
  database: raft_test
  username: postgres
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

before_script:
  - "psql -c 'create database raft_test;' -U postgres"
